### ISSUE TITLE
Suggestion: Use the Rust implementation of xxHash

### ISSUE THREAD

**Issue by mardukbp** [koraa/huniq#15]
Using a C library complicates the compilation, since it requires that the Clang compiler be present.

xxHash has already been [implemented in Rust](https://github.com/shepmaster/twox-hash). If there is a good reason to not use this crate, then it would be great to provide precompiled binaries of huniq.

**Comment by koraa** [comment]
XXHash has been implemented in rust; XXH3 (which is a lot faster) has not… Can you point me at a XXH3 implementation in rust?

**Comment by mardukbp** [comment]
There is a [PR](https://github.com/shepmaster/twox-hash/pull/39) for the crate mentioned above implementing XXH3 in Rust.

I would like to use huniq as a cross-platform uniq, that I can easily install with cargo. Maybe I will just have to write my own inspired by your post in Medium.

**Comment by mardukbp** [comment]
I just had a look at the code of huniq. It seems to me that it would not require much effort to offer the possibility to choose between the Rust implementation of XXHash and the bindings to the C implementation of XXH3. That way people who are willing to sacrifice performance for ease of installation can benefit from your effort too :)

**Comment by koraa** [comment]
That is great! We can try to move to that once the PR is merged. I would be happy to accept a PR that adds a feature flag!

**Comment by alexmaco** [comment]
Imo, a feature flag can make the rust implementation much less useful, since most users will do `cargo install huniq`, and still use xxhash. Assuming that benchmarking (on diverse data, with various amounts of lines, length distribution and ordering) shows that using twox-hash is at least as fast as xxhash, would you consider accepting a PR that completely replaces xxhash ?

**Comment by koraa** [comment]
twox implements xxhash, this uses xxh3 which are separate algorithims…
[Benchmarks have shown](https://medium.com/adobetech/filtering-duplicates-on-the-command-line-30x-faster-than-sort-uniq-96ca5f7b4277) that xxh3 is quicker in one shot mode, but at this point I am ready to question the validity of those benchmarks…

The benchmarks need to be redone, this time in proper rust…

I'd say if xxh3 is to be replaced, it should be replaced by ahash not twox…
